# Generated by Django 5.2.9 on 2025-12-29 06:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('response_message', models.TextField(blank=True, help_text='Message about response time (e.g., "We typically respond within 24-48 hours...")', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'db_table': 'contact_info',
            },
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='contact_sub_is_read_cdea5f_idx',
            old_name='contact_sub_is_read_idx',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='contact_sub_created_54b02f_idx',
            old_name='contact_sub_created_idx',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='contact_sub_email_903821_idx',
            old_name='contact_sub_email_idx',
        ),
    ]
