# Generated by Django 5.2.9 on 2025-12-29 09:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_contactinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='response_message',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Additional comments or remarks for contact information', max_length=1000),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='opening_hours_friday',
            field=models.CharField(blank=True, default='6:00 AM - 8:00 PM', help_text='Opening hours for Friday (e.g., "6:00 AM - 8:00 PM")', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='opening_hours_monday',
            field=models.CharField(blank=True, default='6:00 AM - 8:00 PM', help_text='Opening hours for Monday (e.g., "6:00 AM - 8:00 PM")', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='opening_hours_saturday',
            field=models.CharField(blank=True, default='6:00 AM - 8:00 PM', help_text='Opening hours for Saturday (e.g., "6:00 AM - 8:00 PM")', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='opening_hours_sunday',
            field=models.CharField(blank=True, default='6:00 AM - 8:00 PM', help_text='Opening hours for Sunday (e.g., "6:00 AM - 8:00 PM")', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='opening_hours_thursday',
            field=models.CharField(blank=True, default='6:00 AM - 8:00 PM', help_text='Opening hours for Thursday (e.g., "6:00 AM - 8:00 PM")', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='opening_hours_tuesday',
            field=models.CharField(blank=True, default='6:00 AM - 8:00 PM', help_text='Opening hours for Tuesday (e.g., "6:00 AM - 8:00 PM")', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='opening_hours_wednesday',
            field=models.CharField(blank=True, default='6:00 AM - 8:00 PM', help_text='Opening hours for Wednesday (e.g., "6:00 AM - 8:00 PM")', max_length=100),
        ),
        migrations.CreateModel(
            name='StoreCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the store/center', max_length=200)),
                ('address', models.TextField(help_text='Full address of the store/center')),
                ('google_map_link', models.URLField(help_text='Google Maps link to the location')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'store_centers',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['is_active'], name='store_cente_is_acti_e69c1f_idx'), models.Index(fields=['order'], name='store_cente_order_a687dc_idx')],
            },
        ),
    ]
