# Generated by Django 5.2.10 on 2026-01-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_homepage_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='corporategiftingsection',
            new_name='corporate_g_is_acti_c7e585_idx',
            old_name='content_corp_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='faq',
            new_name='faqs_is_acti_3459f3_idx',
            old_name='content_faq_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='faq',
            new_name='faqs_order_d2a62f_idx',
            old_name='content_faq_order_idx',
        ),
        migrations.RenameIndex(
            model_name='herosection',
            new_name='hero_sectio_is_acti_63a05e_idx',
            old_name='content_hero_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='seasonalsection',
            new_name='seasonal_se_is_acti_fd25ac_idx',
            old_name='content_seasonal_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='seasonalsection',
            new_name='seasonal_se_start_d_f810ed_idx',
            old_name='content_seasonal_dates_idx',
        ),
        migrations.RenameIndex(
            model_name='trustbaritem',
            new_name='trust_bar_i_is_acti_448fa9_idx',
            old_name='content_trustbar_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='trustbaritem',
            new_name='trust_bar_i_order_bac263_idx',
            old_name='content_trustbar_order_idx',
        ),
    ]
