# Generated by Django 5.2.10 on 2026-02-01 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_rename_content_corp_is_active_idx_corporate_g_is_acti_c7e585_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandStorySection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Why Dolce Fiore', max_length=200)),
                ('subtitle', models.CharField(default='Health-first indulgence, artisan-made, and packaging that becomes part of the gift.', max_length=300)),
                ('features', models.JSONField(default=list, help_text='List of feature bullet points (e.g. ["Health-first indulgence", "Artisan-made"])')),
                ('cta_text', models.CharField(default='Read the full story', max_length=50)),
                ('cta_link', models.CharField(default='/about', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand Story Section',
                'verbose_name_plural': 'Brand Story Sections',
                'db_table': 'brand_story_sections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='brand_story_is_acti_bb17e1_idx')],
            },
        ),
    ]
