# Generated by Django 5.2.9 on 2025-12-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_migrate_product_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='categories_slug_b4303a_idx',
            old_name='categories_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='categories_is_acti_aae090_idx',
            old_name='categories_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_subcate_3e1ea0_idx',
            old_name='products_subcategory_idx',
        ),
        migrations.RenameIndex(
            model_name='subcategory',
            new_name='subcategori_categor_8ba7b7_idx',
            old_name='subcategories_category_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='subcategory',
            new_name='subcategori_is_acti_fa690c_idx',
            old_name='subcategories_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='tags_slug_c72f9b_idx',
            old_name='tags_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='tags_is_acti_f35278_idx',
            old_name='tags_is_active_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.tag'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_4083ff_idx'),
        ),
    ]
