# Generated by Django 5.2.10 on 2026-01-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_homepage_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='categories_feature_34f2bc_idx',
            old_name='products_cat_featured_idx',
        ),
    ]
